build_from: 
  aarch64: ghcr.io/hassio-addons/base/aarch64:15.0.7
  amd64: ghcr.io/hassio-addons/base/amd64:15.0.7
  armhf: ghcr.io/hassio-addons/base/armhf:15.0.7
  armv7: ghcr.io/hassio-addons/base/armv7:15.0.7
  i386: ghcr.io/hassio-addons/base/i386:15.0.7
squash: false
codenotary:
  base_image: codenotary@frenck.dev
  signer: hans@expaso.nl
